spring:
  thymeleaf:
    cache: false
  application:
    name: roadanalyzer
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # Включает консоль H2
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholders:
      proto_user_db: admin_db
  mail:
    verification-required: false
    host: smtp.rambler.ru
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_APP_PASSWORD
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      # mail.debug: true
      # mail.smtp.ssl.trust: smtp.rambler.ru
      # mail.transport.protocol: smtp
  config:
    import: "optional:classpath:application-secret.yml"

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  servlet:
    session:
      timeout: 30d  # time life session
      cookie:
        max-age: 30d  # time life cookies