CREATE SEQUENCE SESSIONS_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_accessed_at TIMESTAMP,
    is_active BOOLEAN NOT NULL
);

ALTER TABLE sessions ALTER COLUMN id SET DEFAULT NEXTVAL('SESSIONS_SEQ');